### PR TITLE
automatically create releases on pushes to master containing the rendered audio file

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Do you want this Action to run on every push and only upload when we're pushing to `master`, or do you want to only run the Action when we're pushing to `master`, which might simplify the release logic? If it's the latter, we can do something like [this](https://help.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration):

```yaml
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```

**Comment by soenkehahn** [comment]
Good question. I want the former.

- I want it to build `looper` and render the audio file on every push to any branch and/or pull-request. This is to make sure that we don't merge anything to master that can't be rendered into an audio file.

- And then on pushes to master I want it to create a new release.

The yaml files are more complicated than I'd like, with the top-level `on` and then the duplicated `if` conditions in the two release steps. But as far as I can tell github doesn't support a good way of DRYing this up yet. E.g. it doesn't support yaml anchors and aliases.

**Comment by vaibhavsagar** [comment]
Ah, in that case the approach you're using seems right to me.

**Review by vaibhavsagar — APPROVED** [review]

**Comment by soenkehahn** [comment]
Great, thanks for the review!

**Pull request merged**
